from config.components.base import env

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default=None)
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=None)
CELERY_CACHE_BACKEND = env("CELERY_CACHE_BACKEND", default=None)

CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TRACK_STARTED = True

FLOWER_HOST = env("FLOWER_HOST", default="http://flower")
FLOWER_PORT = env("FLOWER_PORT", default=5555)
FLOWER_URL_PREFIX = env("FLOWER_URL_PREFIX", default="celery")
