"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from split_settings.tools import include

include(
    "components/base.py",
    "components/apps.py",
    "components/middlewares.py",
    "components/templates.py",
    "components/databases.py",
    "components/static_and_media.py",
    "components/rest_framework.py",
    "components/simple_jwt.py",
    "components/spectacular.py",
    "components/auth.py",
    "components/otel.py",
    "components/sentry.py",
    "components/celery.py",
)
