# Generated by Django 5.0.3 on 2024-04-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0001_create_mailing_task_and_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingtemplate",
            name="users_selector",
            field=models.JSONField(blank=True, default=dict, verbose_name="users selector"),
        ),
    ]
