version: '3.9'

x-default-settings: &default-settings
  env_file: ./.env
  restart: always

services:
  websocket-sender:
    container_name: websocket-sender
    <<: *default-settings
    build:
      context: .
      args:
        REQUIREMENTS_DEV: false
    ports:
      - "${WEBSOCKET_SENDER_PORT}:8080"
    volumes:
      - ./src:/app/src
#      - ./tests:/app/tests/
    command: python /app/src/main.py
    depends_on:
      - rabbit
    profiles: [websocket]

  rabbit:
    image: rabbitmq:3.13-management
    <<: *default-settings
    ports:
      - "${RABBIT_PORT}:5672"
      - "${RABBIT_UI_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
#      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbit_volume:/var/lib/rabbitmq


